name: Build and Deploy

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_AUTH }}
      
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USER }}/go-metrics:latest \
            .
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/go-metrics:latest